In [1]:
import pandas as pd
import numpy as np
import matplotlib as plot

In [2]:
df= pd.read_csv(r'/Users/rahulpoojith/Documents/Excelr Datasets/Machine Learning Datasets/anime.csv')

In [3]:
df.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [4]:
df.tail()

anime_id                                               name   genre  \
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami  Hentai   
12290      5543                                        Under World  Hentai   
12291      5621                     Violence Gekiga David no Hoshi  Hentai   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...  Hentai   
12293     26081                   Yasuji no Pornorama: Yacchimae!!  Hentai   

        type episodes  rating  members  
12289    OVA        1    4.15      211  
12290    OVA        1    4.28      183  
12291    OVA        4    4.88      219  
12292    OVA        1    4.98      175  
12293  Movie        1    5.46      142

In [5]:
df.shape

(12294, 7)

In [6]:
df.rating.unique()

array([ 9.37,  9.26,  9.25,  9.17,  9.16,  9.15,  9.13,  9.11,  9.1 ,
        9.06,  9.05,  9.04,  8.98,  8.93,  8.92,  8.88,  8.84,  8.83,
        8.82,  8.81,  8.8 ,  8.78,  8.77,  8.76,  8.75,  8.74,  8.73,
        8.72,  8.71,  8.69,  8.68,  8.67,  8.66,  8.65,  8.64,  8.62,
        8.61,  8.6 ,  8.59,  8.58,  8.57,  8.56,  8.55,  8.54,  8.53,
        8.52,  8.51,  8.5 ,  8.49,  8.48,  8.47,  8.46,  8.45,  8.44,
        8.43,  8.42,  8.41,  8.4 ,  8.39,  8.38,  8.37,  8.36,  8.35,
        8.34,  8.33,  8.32,  8.31,  8.3 ,  8.29,  8.28,  8.27,  8.26,
        8.25,  8.24,  8.23,  8.22,  8.21,  8.2 ,  8.19,  8.18,  8.17,
        8.16,  8.15,  8.14,  8.13,  8.12,  8.11,  8.1 ,  8.09,  8.08,
        8.07,  8.06,  8.05,  8.04,  8.03,  8.02,  8.01,  8.  ,  7.99,
        7.98,  7.97,  7.96,  7.95,  7.94,  7.93,  7.92,  7.91,  7.9 ,
        7.89,  7.88,  7.87,  7.86,  7.85,  7.84,  7.83,  7.82,  7.81,
        7.8 ,  7.79,  7.78,  7.77,  7.76,  7.75,  7.74,  7.73,  7.72,
        7.71,  7.7 ,

In [7]:
df.anime_id.unique()

array([32281,  5114, 28977, ...,  5621,  6133, 26081])

In [8]:
df.name.unique()

array(['Kimi no Na wa.', 'Fullmetal Alchemist: Brotherhood', 'Gintama°',
       ..., 'Violence Gekiga David no Hoshi',
       'Violence Gekiga Shin David no Hoshi: Inma Densetsu',
       'Yasuji no Pornorama: Yacchimae!!'], dtype=object)

In [9]:
df.genre.unique()

array(['Drama, Romance, School, Supernatural',
       'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen',
       'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
       ..., 'Hentai, Sports', 'Drama, Romance, School, Yuri',
       'Hentai, Slice of Life'], dtype=object)

In [10]:
df.type.unique()

array(['Movie', 'TV', 'OVA', 'Special', 'Music', 'ONA', nan], dtype=object)

In [11]:
df.episodes.unique()

array(['1', '64', '51', '24', '10', '148', '110', '13', '201', '25', '22',
       '75', '4', '26', '12', '27', '43', '74', '37', '2', '11', '99',
       'Unknown', '39', '101', '47', '50', '62', '33', '112', '23', '3',
       '94', '6', '8', '14', '7', '40', '15', '203', '77', '291', '120',
       '102', '96', '38', '79', '175', '103', '70', '153', '45', '5',
       '21', '63', '52', '28', '145', '36', '69', '60', '178', '114',
       '35', '61', '34', '109', '20', '9', '49', '366', '97', '48', '78',
       '358', '155', '104', '113', '54', '167', '161', '42', '142', '31',
       '373', '220', '46', '195', '17', '1787', '73', '147', '127', '16',
       '19', '98', '150', '76', '53', '124', '29', '115', '224', '44',
       '58', '93', '154', '92', '67', '172', '86', '30', '276', '59',
       '72', '330', '41', '105', '128', '137', '56', '55', '65', '243',
       '193', '18', '191', '180', '91', '192', '66', '182', '32', '164',
       '100', '296', '694', '95', '68', '117', '151', '130',

In [12]:
df.members.unique()

array([200630, 793665, 114262, ...,  27411,  57355,    652])

In [13]:
df.describe()

anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [14]:
df.isnull().any()

anime_id    False
name        False
genre        True
type         True
episodes    False
rating       True
members     False
dtype: bool

In [15]:
df = df.select_dtypes(include='object')  ## Find the categorical variable

In [16]:
df

name  \
0                                         Kimi no Na wa.   
1                       Fullmetal Alchemist: Brotherhood   
2                                               Gintama°   
3                                            Steins;Gate   
4                                          Gintama&#039;   
...                                                  ...   
12289       Toushindai My Lover: Minami tai Mecha-Minami   
12290                                        Under World   
12291                     Violence Gekiga David no Hoshi   
12292  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  
0                   Drama, Romance, School, Supernatural  Movie        1  
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64  
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51  
3                                       Sci-Fi, Thriller     TV       24  
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51  
...                                                  ...    ...      ...  
12289                                             Hentai    OVA        1  
12290                                             Hentai    OVA        1  
12291                                             Hentai    OVA        4  
12292                                             Hentai    OVA        1  
12293                                             Hentai  Movie        1  

[12294 rows x 4 columns]

In [17]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print("Categorical Columns:", categorical_cols)

Categorical Columns: Index(['name', 'genre', 'type', 'episodes'], dtype='object')


In [18]:
for col in df.columns:
    unique_vals = df[col].unique()
    print(f"Column: {col}, Unique Values: {unique_vals}")

Column: name, Unique Values: ['Kimi no Na wa.' 'Fullmetal Alchemist: Brotherhood' 'Gintama°' ...
 'Violence Gekiga David no Hoshi'
 'Violence Gekiga Shin David no Hoshi: Inma Densetsu'
 'Yasuji no Pornorama: Yacchimae!!']
Column: genre, Unique Values: ['Drama, Romance, School, Supernatural'
 'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen'
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen' ...
 'Hentai, Sports' 'Drama, Romance, School, Yuri' 'Hentai, Slice of Life']
Column: type, Unique Values: ['Movie' 'TV' 'OVA' 'Special' 'Music' 'ONA' nan]
Column: episodes, Unique Values: ['1' '64' '51' '24' '10' '148' '110' '13' '201' '25' '22' '75' '4' '26'
 '12' '27' '43' '74' '37' '2' '11' '99' 'Unknown' '39' '101' '47' '50'
 '62' '33' '112' '23' '3' '94' '6' '8' '14' '7' '40' '15' '203' '77' '291'
 '120' '102' '96' '38' '79' '175' '103' '70' '153' '45' '5' '21' '63' '52'
 '28' '145' '36' '69' '60' '178' '114' '35' '61' '34' '109' '20' '9' '49'
 '366' '97' '48' '78' '35

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
# Instantiate LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to each categorical column
for col in categorical_cols:
    df[col + '_encoded'] = le.fit_transform(df[col])

# Drop the original categorical columns if no longer needed
df = df.drop(columns=categorical_cols)

In [21]:
print(df.head())

   name_encoded  genre_encoded  type_encoded  episodes_encoded
0          5412           2686             0                 0
1          2848            161             5               147
2          3346            534             5               132
3         10259           3240             5                84
4          3337            534             5               132


In [22]:
# Encode all columns in the DataFrame
df_encoded = df.apply(le.fit_transform)
df_encoded

name_encoded  genre_encoded  type_encoded  episodes_encoded
0              5412           2686             0                 0
1              2848            161             5               147
2              3346            534             5               132
3             10259           3240             5                84
4              3337            534             5               132
...             ...            ...           ...               ...
12289         11144           2903             3                 0
12290         11418           2903             3                 0
12291         11562           2903             3               118
12292         11563           2903             3                 0
12293         11904           2903             0                 0

[12294 rows x 4 columns]

## Split the dataset into Training and Testing

In [23]:
fetures = df_encoded.drop(columns= ['type_encoded'])
target = df_encoded['type_encoded']

In [24]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(fetures, target, test_size=0.2, random_state=50)

In [25]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(X_test.shape)

(9835, 3)
(2459, 3)
(9835,)
(2459, 3)


In [26]:
len(df.name_encoded.unique())

12292

In [27]:
len(df.genre_encoded.unique())

3265

In [28]:
len(df.episodes_encoded.unique())

187

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
## Item Based 

In [31]:
df1= df.pivot_table(index='genre_encoded',columns='name_encoded',values='type_encoded')
df1.fillna(0,axis=1,inplace=True)

In [32]:
df1

name_encoded   0      1      2      3      4      5      6      7      8      \
genre_encoded                                                                  
0                0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1                0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2                0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3                0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4                0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...              ...    ...    ...    ...    ...    ...    ...    ...    ...   
3260             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3261             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3262             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3263             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3264             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

name_encoded   9      ...  12282  12283  12284  12285  12286  12287  12288  \
genre_encoded         ...                                                    
0                0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1                0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2                0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3                0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4                0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...              ...  ...    ...    ...    ...    ...    ...    ...    ...   
3260             0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3261             0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3262             0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3263             0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3264             0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

name_encoded   12289  12290  12291  
genre_encoded                       
0                0.0    0.0    0.0  
1                0.0    0.0    0.0  
2                0.0    0.0    0.0  
3                0.0    0.0    0.0  
4                0.0    0.0    0.0  
...              ...    ...    ...  
3260             0.0    0.0    0.0  
3261             0.0    0.0    0.0  
3262             0.0    0.0    0.0  
3263             0.0    0.0    0.0  
3264             0.0    0.0    0.0  

[3265 rows x 12292 columns]

In [33]:
similarities=cosine_similarity(df1)
similarities

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [34]:
df1.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       3255, 3256, 3257, 3258, 3259, 3260, 3261, 3262, 3263, 3264],
      dtype='int64', name='genre_encoded', length=3265)

In [35]:
similar=sorted(list(enumerate(similarities[6])),key=lambda x: x[1],reverse=True)[1:5]
similar

[(0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0)]

## User Based Similarity

In [36]:
df2= df.pivot_table(index='genre_encoded',columns='name_encoded',values='type_encoded')
df2.fillna(0,axis=1,inplace=True)
df2

name_encoded   0      1      2      3      4      5      6      7      8      \
genre_encoded                                                                  
0                0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1                0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2                0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3                0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4                0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...              ...    ...    ...    ...    ...    ...    ...    ...    ...   
3260             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3261             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3262             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3263             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3264             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

name_encoded   9      ...  12282  12283  12284  12285  12286  12287  12288  \
genre_encoded         ...                                                    
0                0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1                0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2                0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3                0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4                0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...              ...  ...    ...    ...    ...    ...    ...    ...    ...   
3260             0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3261             0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3262             0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3263             0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3264             0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

name_encoded   12289  12290  12291  
genre_encoded                       
0                0.0    0.0    0.0  
1                0.0    0.0    0.0  
2                0.0    0.0    0.0  
3                0.0    0.0    0.0  
4                0.0    0.0    0.0  
...              ...    ...    ...  
3260             0.0    0.0    0.0  
3261             0.0    0.0    0.0  
3262             0.0    0.0    0.0  
3263             0.0    0.0    0.0  
3264             0.0    0.0    0.0  

[3265 rows x 12292 columns]

In [37]:
similarities1= cosine_similarity(df2)
similarities1.shape
np.fill_diagonal(similarities1,0)

In [38]:
df_new=pd.DataFrame(similarities1)
df_new.index=df.genre_encoded.unique()
df_new.columns=df.genre_encoded.unique()

In [39]:
df_new

2686  161   534   3240  1818  363   2623  2492  2713  777   ...  526   \
2686   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
161    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
534    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3240   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1818   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
391    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
527    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2935   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2687   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2933   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      1007  2059  2931  481   391   527   2935  2687  2933  
2686   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
161    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
534    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3240   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1818   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
391    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
527    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2935   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2687   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2933   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[3265 rows x 3265 columns]

In [40]:
from sklearn.ensemble import RandomForestRegressor

# Initialize the model
rand_for_regressor = RandomForestRegressor()

# Fit the model
rand_for_regressor.fit(X_train, y_train)

RandomForestRegressor()

In [41]:
y_pred = rand_for_regressor.predict(X_test)

In [42]:
y_pred

array([3.21, 0.28, 4.73, ..., 3.  , 3.93, 4.21])

Interview Questions:
1. Can you explain the difference between user-based and item-based collaborative filtering?
2. What is collaborative filtering, and how does it work?

1. User-Based vs. Item-Based Collaborative Filtering
User-based collaborative filtering recommends items to a user based on the preferences of similar users. It finds users with similar tastes and suggests items that those users have liked.   

Item-based collaborative filtering recommends items to a user based on their similarity to other items the user has liked. It finds items that are similar to each other and suggests those similar items to the user.

Key Differences:

Similarity Metric: User-based uses similarity between users, while item-based uses similarity between items.
Scalability: Item-based can be more scalable for large datasets as it involves calculating similarity between items once, while user-based needs to calculate similarity between users for each recommendation.
Sparsity: Item-based can handle sparse data better as it doesn't rely on finding similar users, which might be difficult in sparse datasets.
2. Collaborative Filtering: How it Works
Collaborative filtering is a technique used to predict a user's preferences for items based on the preferences of other users. It assumes that users who have similar tastes will also have similar preferences for new items.


Steps involved in collaborative filtering:

Data Collection: Gather a dataset of user-item interactions (e.g., ratings, purchases, clicks).
Similarity Calculation: Calculate the similarity between users or items based on their interactions. Common similarity metrics include Pearson correlation, cosine similarity, and Euclidean distance.
Recommendation Generation: Use the calculated similarities to generate recommendations. For example, in user-based filtering, recommend items that similar users have liked, while in item-based filtering, recommend items that are similar to the user's liked items.
Types of Collaborative Filtering:

Memory-based: Uses the entire dataset to calculate similarities and generate recommendations.
Model-based: Uses machine learning models (e.g., matrix factorization) to learn latent factors that represent user preferences and item characteristics.
Advantages of Collaborative Filtering:

No need for explicit item features: It relies solely on user interactions.
Can handle a variety of data types: Ratings, purchases, clicks, etc.
Effective for personalized recommendations: Can tailor recommendations to individual users.
Disadvantages of Collaborative Filtering:

Cold-start problem: Difficulty recommending items to new users or for items with few ratings.
Scalability issues: Can be computationally expensive for large datasets.
Sensitivity to data sparsity: May struggle to find similar users or items in sparse datasets.

Sources and related content
